name: demo_1
description: ''
version: 0.0.1
author: poojas@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: demo_1
  parentArtefactID: poojasprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-03-31 07:24:02'
pipelines:
  pipelines/demoPip:
    name: demoPip
    description: ''
    author: poojas@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-03-20 09:56:01'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customer_orders
    subgraphs:
    - subgraphs/join_subgraph
    dependencies: {}
  pipelines/demoPip2:
    name: demoPip2
    description: ''
    author: poojas@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-03-20 10:27:26'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customers:
    name: customers
    description: ''
    author: poojas@prophecy.io
    createdAt: '2023-03-20 10:02:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 647
        datasetType: File
        description: ''
        author: poojas@prophecy.io
        createdAt: '2023-03-20 10:02:59'
  datasets/orders:
    name: orders
    description: ''
    author: poojas@prophecy.io
    createdAt: '2023-03-20 10:04:10'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 647
        datasetType: File
        description: ''
        author: poojas@prophecy.io
        createdAt: '2023-03-20 10:04:10'
  datasets/customer_orders:
    name: customer_orders
    description: ''
    author: poojas@prophecy.io
    createdAt: '2023-03-20 10:14:08'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 647
        datasetType: File
        description: ''
        author: poojas@prophecy.io
        createdAt: '2023-03-20 10:14:08'
templates: {}
jobs:
  jobs/demo_job:
    name: demo_job
    description: ''
    fabricUID: 647
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: Small
    scheduleCron: 0 0 0/1 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/demoPip
    - pipelines/demoPip2
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2023-03-20 10:29:48'
    author: poojas@prophecy.io
functions:
  author: null
  createdAt: '2023-03-31 07:24:02'
  gems: {}
  udfs:
    udfs/addten:
      name: addten
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: poojas@prophecy.io
      createdAt: '2022-12-15 18:04:50'
  udafs: {}
  expressions: {}
subgraphs:
  subgraphs/join_subgraph:
    name: join_subgraph
    description: test description
    author: poojas@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2023-03-20 10:27:09'
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
